"use strict";
exports.__esModule = true;
var Token;
(function (Token) {
    Token[Token["BooleanLiteral"] = 1] = "BooleanLiteral";
    Token[Token["EOF"] = 2] = "EOF";
    Token[Token["Identifier"] = 3] = "Identifier";
    Token[Token["Keyword"] = 4] = "Keyword";
    Token[Token["NullLiteral"] = 5] = "NullLiteral";
    Token[Token["NumericLiteral"] = 6] = "NumericLiteral";
    Token[Token["Punctuator"] = 7] = "Punctuator";
    Token[Token["StringLiteral"] = 8] = "StringLiteral";
})(Token = exports.Token || (exports.Token = {}));
;
exports.TokenName = {};
exports.TokenName[1] = 'Boolean';
exports.TokenName[2] = '<end>';
exports.TokenName[3] = 'Identifier';
exports.TokenName[4] = 'Keyword';
exports.TokenName[5] = 'Null';
exports.TokenName[6] = 'Numeric';
exports.TokenName[7] = 'Punctuator';
exports.TokenName[8] = 'String';
